import { User } from "./User"

export const USERS: User[] = [
    {
        id: "IU1685",
        profile: "assets/image.png",
        firstname: "Lindsey",
        lastname: "Stroud",
        emailid: "lindsey.stroud@gmail.com",
        role: "Admin",
        usertype: "Internal",
        customers: 6,
        updatedOnDate: "16 Feb 2021",
        updatedOnTime: "02:30 Pm",
        status: "Active",
    },
    {
        id: "IU1234",
        profile: "assets/image 2.png",
        firstname: "Nicci",
        lastname: "Troiani",
        emailid: "nicci.troiani@gmail.com",
        role: "",
        usertype: "Internal",
        customers: 0,
        updatedOnDate: "08 Feb 2021",
        updatedOnTime: "11:30 Am",
        status: "Draft",
    },
    {
        id: "IU2456",
        profile: "assets/image 3.png",
        firstname: "Geroge",
        lastname: "Fields",
        emailid: "geroge.fields@gmail.com",
        role: "Sales Head",
        usertype: "Internal",
        customers: 3,
        updatedOnDate: "28 Feb 2021",
        updatedOnTime: "04:30 Pm",
        status: "Pending Approval",
    },
    {
        id: "PU1256",
        profile: "assets/image 3-2.png",
        firstname: "Rebecca",
        lastname: "Moore",
        emailid: "rebecca.moore@gmail.com",
        role: "HR Manager",
        usertype: "Partner",
        customers: 8,
        updatedOnDate: "20 Jan 2021",
        updatedOnTime: "11:55 Am",
        status: "Active",
    },
    {
        id: "CU2456",
        profile: "assets/image 3-3.png",
        firstname: "Jane",
        lastname: "Doe",
        emailid: "jane.doe@gmail.com",
        role: "Design Head",
        usertype: "Client",
        customers: 0,
        updatedOnDate: "21 Dec 2020",
        updatedOnTime: "11:30 Am",
        status: "Inactive",
    },
    {
        id: "EU2456",
        profile: "assets/image 2-2.png",
        firstname: "Jones",
        lastname: "Dermot",
        emailid: "jones.dermot@gmail.com",
        role: "Project Lead",
        usertype: "External",
        customers: 0,
        updatedOnDate: "08 Dec 2020",
        updatedOnTime: "10:30 Am",
        status: "Rejected",
    },
]